missions/urls.py
from django.urls import path
from . import views

#MAPPING BETWEEN ADDRESSES AND FUNCTIONS

urlpatterns = [
    path('', views.home, name='home'),
    path('mission/<int:id>', views.mission, name='mission'),
    path('elon/', views.elon, name='elon'),
    path('tesla/', views.tesla, name='tesla'),
    path('astros/', views.astronauts, name='astronauts'),
    path('astros/like/', views.like_astro, name='like-astro'),
    path('add_astro/', views.add_astro, name='add-astronaut'),
    path('add_mission/', views.add_mission, name='add-mission'),
    path('see_rockets/', views.AllRockets.as_view(), name='see-rockets'),
    path('rocket_details/<int:pk>', views.RocketDeets.as_view(), name='rocket-details'),
    path('add_rocket/', views.AddRocket.as_view(), name='add-rocket'),

    # path('custom_login', views.custom_login, name='custom-login')  #If we build Login ourselves
]

spacex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('missions.urls'))
]

missions/models.py
from django.db import models


class Astro(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=30)
    rank = models.CharField(max_length=20)
    likes = models.IntegerField(default=0)

    def __repr__(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"Astronaut: ID: {self.id}: {self.first_name} {self.last_name}"


class MedProfile(models.Model):
    astro = models.OneToOneField(Astro, on_delete=models.CASCADE, primary_key=True)
    height = models.FloatField(default=0)
    weight = models.FloatField(default=0)
    clearance = models.BooleanField(default=True)

    def __repr__(self):
        return f"Medical Profile for {self.astro}"


class Mission(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    pilot = models.ForeignKey(Astro, on_delete=models.SET_NULL, null=True)
    launch_date = models.CharField(max_length=50, null=True)
    training_mission = models.BooleanField(default=False)

    def __repr__(self):
        return f"Mission {self.id}: {self.name}"

    def __str__(self):
        return f"Mission {self.id}: {self.name}"

    def get_pilot(self):
        return self.pilot or "No Pilot Selected Yet"


class Rocket(models.Model):
    name = models.CharField(max_length=50)
    fuel_capacity = models.IntegerField(default=0)
    max_weight = models.IntegerField(default=0)
    thrust = models.IntegerField(default=0)
    image = models.URLField(max_length=200)
    missions = models.ManyToManyField(Mission, related_name="all_rockets")


    def __repr__(self):
        return f"Rocket: {self.name}"

    def __str__(self):
        return f"Rocket: {self.name}"

missions/forms.py
from django import forms
from .models import Mission, Rocket

        
def check_young(age):
    if age < 30:
        raise forms.ValidationError(f'You are not old enough to be an astronaut')

class AddAstroForm(forms.Form):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(
        label="",
        widget = forms.TextInput(
            attrs={
                'placeholder': 'Last Name',
                'class': 'form-control'
            })
    )
    
    age = forms.IntegerField(
        validators=[check_young]
    )
    rank = forms.CharField(
        required=True,
        label="Type your Rank", 
        help_text='You better be in the military.', 
        error_messages={'required': 'Please enter a valid Rank'}
    )
    


class AddMissionForm(forms.ModelForm):
    class Meta:      
        model = Mission
        fields = '__all__'



class AddRocketForm(forms.ModelForm):
    class Meta:      
        model = Rocket
        fields = '__all__'

    

missions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Mission, Astro, Rocket
from django.http import Http404
from cprint import cprint
from .forms import AddAstroForm, AddMissionForm, AddRocketForm
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy
from django.contrib import messages
import json

from django.contrib.auth.decorators import login_required


def home(request):

    missions = Mission.objects.all()

    context = {
        'all_missions': missions,
        'director': 'Paul Tomkins'
    }

    html_page = render(request, 'home.html', context)

    return html_page


def elon(request):
    return render(request, 'elon.html')


def mission(request, id):
    # mission = get_object_or_404(Mission, pk=id)
    # return render(request, 'mission_details.html', {'mission': mission})
    try:
        mission = get_object_or_404(Mission, pk=id)
        return render(request, 'mission_details.html', {'mission': mission})
    except Http404:
        return render(request, '404.html')
        

def tesla(request):
    return redirect("http://tesla.com")

@login_required
def astronauts(request):
    return render(request, 'astronauts.html', {'astronauts': Astro.objects.all()})

def like_astro(request):
    data = json.loads(request.body)
    astro = Astro.objects.get(id=data['astro_id'])
    action = data['action']
    if action == 'like':
        astro.likes += 1
    if action == 'dislike':
        astro.likes -= 1
    astro.save()
    return HttpResponse(json.dumps({'likes': astro.likes}))

# Handled with Regular Forms
def add_astro(request):

    if request.method == "GET":
        myform = AddAstroForm()
        return render(request, 'add_astro.html', {'myform':myform})

    if request.method == "POST":

        myform = AddAstroForm(request.POST)

        if myform.is_valid():
            first_name=myform.cleaned_data['first_name']
            last_name=myform.cleaned_data['last_name']
            age=myform.cleaned_data['age']
            rank=myform.cleaned_data['rank']

            if age > 60:
                messages.info(request, 'Your Astronauts are getting old')
                messages.success(request, 'This is an example of a success message')
                messages.warning(request, 'This is an example of a warning message')
                return render(request, 'add_astro.html', {'myform':myform})

            
            a1 = Astro(first_name=first_name, last_name=last_name, age=age, rank=rank)
            a1.save()

            return redirect('astronauts')

        else:
            return render(request, 'add_astro.html', {'myform':myform})


# Handled with Model Forms
def add_mission(request):

    if request.method == "GET":
        return render(request, 'add_mission.html', {'form': AddMissionForm()})

    if request.method == "POST":
        form = AddMissionForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            return render(request, 'add_mission.html', {'form': form})


class AllRockets(ListView):
    model = Rocket
    template_name = "rockets.html"

    #OPTIONAL CHANGES
    ordering = ['name']
    queryset = Rocket.objects.filter(fuel_capacity__gt=-1)


class RocketDeets(DetailView):
    model = Rocket
    template_name = "rocket_deets.html"
    
    # OPTIONALLY OVERRIDE get_context_data
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = "SpaceX is the best!"
        return context


class AddRocket(CreateView):
    form_class = AddRocketForm
    template_name = 'add_rocket.html'
    success_url = reverse_lazy('see-rockets')





# EXAMPLE IF WE BUILT LOGIN OURSELVES.

# from django.contrib.auth import authenticate, login
# def custom_login(request):
    
#     username = request.POST.get('username')
#     password = request.POST.get('password')

#     user = authenticate(username=username, password=password)

#     if user is not None:
#         login(request, user)
#         return redirect('home')
#     else:
#         return redirect('login')

missions/templates/add_astro.html
{% extends 'base.html' %}

{% block content %}
<h1>Add Astronaut</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{myform.as_table}}
        </table>
        <input type="submit">
    </form>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}


{% endblock %}

missions/templates/add_mission.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Add Mission</h1>
<div class="row">
    <div class="col col-4">
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary" type="submit">Add</button>
        </form>
    </div>
</div>
{% endblock %}

missions/templates/add_rocket.html
{% extends 'base.html' %}

{% block content %}
<h1>Add Rocket</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit">
    </form>
{% endblock %}

missions/templates/astronauts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Our Famous Astros</h1>

    {% if astronauts %}
        <h3>Pilots</h3>
        <table class="table table-border table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Likes</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for astro in astronauts %}
                <tr>
                    <td>{{astro}}</td>
                    <td id="astro_like_{{astro.id}}">{{astro.likes}}</td>
                    <td>
                        <button type='button' action="like" astro_id={{astro.id}} class="btn btn-primary btn-sm">Like</button>
                        <button type='button' action="dislike" astro_id={{astro.id}} class="btn btn-danger btn-sm">Dislike</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    {% endif %}
    
    <a class="btn btn-primary" href="{% url 'home' %}">Home</a>
    <a class="btn btn-success" href="{% url 'add-astronaut' %}">Add Astronaut</a>
    
{% endblock %}


{% block js %}
        <script type="text/javascript">

            const url = "{% url 'like-astro' %}"

             // add event listner
             document.querySelector('table').addEventListener('click', function(event){
                // listen for clicks on the like buttons
                if (event.target.type != 'button'){
                    return;
                }

                // extract the astro id from the like button
                const astro_id = event.target.getAttribute("astro_id");
                const action = event.target.getAttribute("action");
                const csrftoken = getCookie('csrftoken');
                const data = {'astro_id': astro_id, 'action':action}
                
                // fetch to the server, sending that id.
                fetch(url, {
                    headers: {'X-CSRFToken': csrftoken},
                    method: 'post',
                    body: (JSON.stringify(data)),
                })
                .then(response => response.json())
                .then(data => update_astro(data, astro_id))
            }) 

            function update_astro(data, astro_id){
                const id = "astro_like_" + astro_id
                target = document.getElementById(id)
                target.innerHTML = data.likes
            }
            
            // Django's way to get a csrf token.

            function getCookie(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            

                

            // response returns.... update the dom
        </script>
{% endblock %}


{% block title%}Missions Page{% endblock %}

missions/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <img src="https://i.imgur.com/pkIJHAE.png" alt="" height=100px width=100%>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% block js %}
    {% endblock %}
</body>
</html>

missions/templates/elon.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>My name is Elon Musk.</h1>

    <img src="{% static 'images/elon.png' %}" alt="" width=150px height=300px>
    
    <p>
        <a class="btn btn-success mt-4" href="{% url 'home' %}">
            Back to Home
        </a>

        <a class="btn btn-warning ml-4 mt-4" href="{% url 'tesla' %}"  target="_blank">
            About Tesla
        </a>

        <a class="btn btn-primary ml-4 mt-4" href="{% url 'login' %}">
            Login
        </a>
    </p>
{% endblock %}


{% block title%}ELONS Page{% endblock %}

missions/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex justify-content-between">
        <h1>Welcome to SpaceX Missions Home Page.</h1>
        {% if not user.is_anonymous %}
        <a href="{% url 'logout' %}">Logout</a>
        {% endif %}
    </div>

    {% if user.is_anonymous %}
    <h2>Welcome Stranger!</h2>
    {% else %}
    <h2>Welcome {{user.get_full_name}}</h2>
    {% endif %}

    <h3>Mission Director</h3>
    <h2>{{director.upper}}</h2>

    {% if all_missions %}
        <h3>Upcoming Missions</h3>
        {% for mission in all_missions %}
        <p>
            {% if mission.training_mission %}
            <a href="{% url 'mission' mission.id %}" class="text-success">{{mission.name}}</a>
            {% else %}
            <a href="{% url 'mission' mission.id %}" class="text-danger">{{mission.name}}</a>
            {% endif %}
        </p>
        {% endfor %}
    {% else %}
        <h3 style="color:red">There are no upcoming missions. Send Help!</h3>
    {% endif %}
    
    <a class="btn btn-primary" href="{% url 'elon' %}">About Our Glorious Leader (Not Kim Jong Un)</a>
    <a class="btn btn-success" href="{% url 'astronauts' %}">Astronauts</a>
    <a class="btn btn-warning" href="{% url 'add-mission' %}">Add Mission</a>
    <p>
        <a class="btn btn-danger" href="{% url 'see-rockets' %}">See Our Rockets</a>
    </p>

{% endblock %}


{% block title%}Missions Page{% endblock %}

missions/templates/mission_details.html
{% extends 'base.html' %}

{% block content %}
    <h1>Mission Details</h1>
    <h3>{{mission.name}}</h3>
    <h4>Piloted By: {{mission.pilot}}</h4>
    <h4>Launch Date: {{mission.launch_date}}</h4>

    {% if not mission.training_mission %}
        <p class="text-danger"> This is not a drill!</p>
    {% else %}
        <p class="text-success"> Enjoy the Simulation</p>
    {% endif %}


    <div style="display: flex; justify-content: space-evenly;">
        {% for rocket in mission.all_rockets.all %}
        <div>
            <img src="{{rocket.image}}" alt="" width=100px height=200px>
            <h4>{{rocket.name}}</h4>
        </div>
        {% endfor %}
    </div>
    

    <a class="btn btn-primary" href="{% url 'home' %}">Back to Home</a>
{% endblock %}

missions/templates/rocket_deets.html
{% extends 'base.html' %}

{% block content %}
<h1>The Rockets</h1>
<h1>{{msg}}</h1>
<p>Name: {{rocket.name}}</p> 
<p>Fuel Capacity: {{rocket.fuel_capacity}} (litres)</p> 
<p>Max Weight: {{rocket.max_weight}} Kg</p> 
<p>Thrust: {{rocket.thrust}} Nm/s</p> 
<p>
    <img src="{{rocket.image}}" alt="" width=100px height=200px>
</p>
<a class="btn btn-secondary" href="{% url 'see-rockets' %}">Back</a>
</p>
{% endblock %}

missions/templates/rockets.html
{% extends 'base.html' %}

{% block content %}
<h1>Our Rockets</h1>
{% for rocket in rocket_list %}
    <p><a href="{% url 'rocket-details' rocket.id %}">{{rocket}}</a></p>
{% endfor %}
<p>
    <a class="btn btn-primary" href="{% url 'add-rocket' %}">Add</a>
    <a class="btn btn-secondary" href="{% url 'home' %}">Back</a>
</p>
{% endblock %}